language: android
jdk: oraclejdk8
sudo: required

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache


install:
  # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
  - if test ! -e $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; then curl https://dl.google.com/android/repository/tools_r25.2.5-linux.zip > $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; fi
  - unzip -n $HOME/android-sdk-dl/tools_r25.2.5-linux.zip -d $HOME/android-sdk

  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;25.0.3'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-25'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;android;m2repository'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;android;support'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository'

env:
  - ANDROID_HOME=$HOME/android-sdk

android:
  components:
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25

env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
    - ANDROID_SDKS=android-14
    - ANDROID_TARGET=android-14

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

#before_install:
#  # TODO: Remove the following line when Travis' platform-tools are updated to v24+
#  - echo yes | android update sdk -a --filter platform-tools --no-ui --force

script:
  - ./gradlew build
  - ./gradlew test connectedAndroidTest --info --stacktrace
